# Generated by Django 4.2.4 on 2023-09-03 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='memeber',
            new_name='member',
        ),
    ]
