# Generated by Django 4.2.4 on 2023-09-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_rename_memeber_group_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='period',
        ),
        migrations.AddField(
            model_name='group',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
