# Generated by Django 4.2.4 on 2023-09-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_remove_group_period_group_duration_group_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='location',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='nation',
            field=models.CharField(max_length=512),
        ),
    ]
