# Generated by Django 4.2.4 on 2023-09-03 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_group_location_alter_group_nation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='duration',
        ),
    ]
