# Generated by Django 4.0.4 on 2023-09-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_emailverification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_certified',
            field=models.BooleanField(default=False),
        ),
    ]
