# Generated by Django 4.0.4 on 2023-09-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_delete_emailverification_user_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
