# Generated by Django 4.0.4 on 2024-01-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
